import type {
  Category,
  PlatformItem,
  ContentTypeItem,
  LanguageItem,
  LocationState,
  LocationDistrict,
} from "./types";
import { INDIA_STATES } from "./india-data";

export const DEFAULT_CATEGORIES: Category[] = [
  { id: "technology", name: "Technology", slug: "technology", icon: "Cpu", themeColor: "#3B82F6", color: "#3B82F6", status: "active", enabled: true, displayOrder: 1, groupCount: 0 },
  { id: "education", name: "Education", slug: "education", icon: "GraduationCap", themeColor: "#8B5CF6", color: "#8B5CF6", status: "active", enabled: true, displayOrder: 2, groupCount: 0 },
  { id: "jobs", name: "Jobs", slug: "jobs", icon: "Briefcase", themeColor: "#F59E0B", color: "#F59E0B", status: "active", enabled: true, displayOrder: 3, groupCount: 0 },
  { id: "business", name: "Business", slug: "business", icon: "Building2", themeColor: "#10B981", color: "#10B981", status: "active", enabled: true, displayOrder: 4, groupCount: 0 },
  { id: "news", name: "News", slug: "news", icon: "Newspaper", themeColor: "#EF4444", color: "#EF4444", status: "active", enabled: true, displayOrder: 5, groupCount: 0 },
  { id: "entertainment", name: "Entertainment", slug: "entertainment", icon: "Film", themeColor: "#EC4899", color: "#EC4899", status: "active", enabled: true, displayOrder: 6, groupCount: 0 },
  { id: "gaming", name: "Gaming", slug: "gaming", icon: "Gamepad2", themeColor: "#6366F1", color: "#6366F1", status: "active", enabled: true, displayOrder: 7, groupCount: 0 },
  { id: "sports", name: "Sports", slug: "sports", icon: "Trophy", themeColor: "#22C55E", color: "#22C55E", status: "active", enabled: true, displayOrder: 8, groupCount: 0 },
  { id: "shopping", name: "Shopping", slug: "shopping", icon: "ShoppingBag", themeColor: "#F43F5E", color: "#F43F5E", status: "active", enabled: true, displayOrder: 9, groupCount: 0 },
  { id: "travel", name: "Travel", slug: "travel", icon: "Compass", themeColor: "#14B8A6", color: "#14B8A6", status: "active", enabled: true, displayOrder: 10, groupCount: 0 },
  { id: "health", name: "Health", slug: "health", icon: "Heart", themeColor: "#10B981", color: "#10B981", status: "active", enabled: true, displayOrder: 11, groupCount: 0 },
  { id: "food", name: "Food", slug: "food", icon: "Utensils", themeColor: "#F97316", color: "#F97316", status: "active", enabled: true, displayOrder: 12, groupCount: 0 },
  { id: "finance", name: "Finance", slug: "finance", icon: "Wallet", themeColor: "#0EA5E9", color: "#0EA5E9", status: "active", enabled: true, displayOrder: 13, groupCount: 0 },
  { id: "real-estate", name: "Real Estate", slug: "real-estate", icon: "Home", themeColor: "#8B5CF6", color: "#8B5CF6", status: "active", enabled: true, displayOrder: 14, groupCount: 0 },
  { id: "room-rent", name: "Room Rent", slug: "room-rent", icon: "Key", themeColor: "#06B6D4", color: "#06B6D4", status: "active", enabled: true, displayOrder: 15, groupCount: 0 },
  { id: "buy-sell", name: "Buy & Sell", slug: "buy-sell", icon: "Tag", themeColor: "#F59E0B", color: "#F59E0B", status: "active", enabled: true, displayOrder: 16, groupCount: 0 },
  { id: "government", name: "Government", slug: "government", icon: "Landmark", themeColor: "#2563EB", color: "#2563EB", status: "active", enabled: true, displayOrder: 17, groupCount: 0 },
  { id: "local-community", name: "Local Community", slug: "local-community", icon: "Users", themeColor: "#14B8A6", color: "#14B8A6", status: "active", enabled: true, displayOrder: 18, groupCount: 0 },
  { id: "religious", name: "Religious", slug: "religious", icon: "Sparkles", themeColor: "#7C3AED", color: "#7C3AED", status: "active", enabled: true, displayOrder: 19, groupCount: 0 },
  { id: "social", name: "Social", slug: "social", icon: "MessageSquare", themeColor: "#EC4899", color: "#EC4899", status: "active", enabled: true, displayOrder: 20, groupCount: 0 },
  { id: "agriculture", name: "Agriculture", slug: "agriculture", icon: "Sprout", themeColor: "#65A30D", color: "#65A30D", status: "active", enabled: true, displayOrder: 21, groupCount: 0 },
  { id: "automobile", name: "Automobile", slug: "automobile", icon: "Car", themeColor: "#475569", color: "#475569", status: "active", enabled: true, displayOrder: 22, groupCount: 0 },
  { id: "movies", name: "Movies", slug: "movies", icon: "Clapperboard", themeColor: "#DC2626", color: "#DC2626", status: "active", enabled: true, displayOrder: 23, groupCount: 0 },
  { id: "music", name: "Music", slug: "music", icon: "Music", themeColor: "#A855F7", color: "#A855F7", status: "active", enabled: true, displayOrder: 24, groupCount: 0 },
  { id: "books", name: "Books", slug: "books", icon: "BookOpen", themeColor: "#0891B2", color: "#0891B2", status: "active", enabled: true, displayOrder: 25, groupCount: 0 },
  { id: "events", name: "Events", slug: "events", icon: "Calendar", themeColor: "#EA580C", color: "#EA580C", status: "active", enabled: true, displayOrder: 26, groupCount: 0 },
  { id: "other", name: "Other", slug: "other", icon: "Folder", themeColor: "#64748B", color: "#64748B", status: "active", enabled: true, displayOrder: 27, groupCount: 0 },
];

export const DEFAULT_PLATFORMS: PlatformItem[] = [
  {
    id: "whatsapp",
    name: "WhatsApp",
    slug: "whatsapp",
    icon: "whatsapp",
    themeColor: "#25D366",
    color: "#25D366",
    badgeColor: "bg-[#25D366]/10 text-[#25D366] border-[#25D366]/20",
    invitePattern: "^https?:\\/\\/(chat\\.whatsapp\\.com|wa\\.me|whatsapp\\.com\\/channel)\\/.+",
    helpText: "Enter WhatsApp Group or Channel invite link (chat.whatsapp.com or wa.me)",
    errorText: "Invalid WhatsApp link",
    status: "active",
    enabled: true,
    displayOrder: 1,
    order: 1,
  },
  {
    id: "telegram",
    name: "Telegram",
    slug: "telegram",
    icon: "telegram",
    themeColor: "#229ED9",
    color: "#229ED9",
    badgeColor: "bg-[#229ED9]/10 text-[#229ED9] border-[#229ED9]/20",
    invitePattern: "^https?:\\/\\/(t\\.me|telegram\\.me)\\/.+",
    helpText: "Enter Telegram Group or Channel link (t.me/...)",
    errorText: "Invalid Telegram link",
    status: "active",
    enabled: true,
    displayOrder: 2,
    order: 2,
  },
  {
    id: "discord",
    name: "Discord",
    slug: "discord",
    icon: "discord",
    themeColor: "#5865F2",
    color: "#5865F2",
    badgeColor: "bg-[#5865F2]/10 text-[#5865F2] border-[#5865F2]/20",
    invitePattern: "^https?:\\/\\/(discord\\.gg|discord\\.com\\/invite)\\/.+",
    helpText: "Enter Discord server invite link (discord.gg/...)",
    errorText: "Invalid Discord link",
    status: "active",
    enabled: true,
    displayOrder: 3,
    order: 3,
  },
  {
    id: "facebook-groups",
    name: "Facebook Groups",
    slug: "facebook-groups",
    icon: "facebook",
    themeColor: "#1877F2",
    color: "#1877F2",
    badgeColor: "bg-[#1877F2]/10 text-[#1877F2] border-[#1877F2]/20",
    invitePattern: "^https?:\\/\\/(facebook\\.com|fb\\.com)\\/.+",
    helpText: "Enter Facebook Group URL",
    errorText: "Invalid Facebook URL",
    status: "active",
    enabled: true,
    displayOrder: 4,
    order: 4,
  },
  {
    id: "instagram-broadcast",
    name: "Instagram Broadcast",
    slug: "instagram-broadcast",
    icon: "instagram",
    themeColor: "#E4405F",
    color: "#E4405F",
    badgeColor: "bg-[#E4405F]/10 text-[#E4405F] border-[#E4405F]/20",
    invitePattern: "^https?:\\/\\/(instagram\\.com|ig\\.me)\\/.+",
    helpText: "Enter Instagram Broadcast channel link",
    errorText: "Invalid Instagram URL",
    status: "active",
    enabled: true,
    displayOrder: 5,
    order: 5,
  },
  {
    id: "x-communities",
    name: "X Communities",
    slug: "x-communities",
    icon: "x",
    themeColor: "#111111",
    color: "#111111",
    badgeColor: "bg-[#111111]/10 text-[#111111] border-[#111111]/20",
    invitePattern: "^https?:\\/\\/(x\\.com|twitter\\.com)\\/.+",
    helpText: "Enter X Community link",
    errorText: "Invalid X URL",
    status: "active",
    enabled: true,
    displayOrder: 6,
    order: 6,
  },
  {
    id: "linkedin-groups",
    name: "LinkedIn Groups",
    slug: "linkedin-groups",
    icon: "linkedin",
    themeColor: "#0A66C2",
    color: "#0A66C2",
    badgeColor: "bg-[#0A66C2]/10 text-[#0A66C2] border-[#0A66C2]/20",
    invitePattern: "^https?:\\/\\/(linkedin\\.com)\\/.+",
    helpText: "Enter LinkedIn Group link",
    errorText: "Invalid LinkedIn URL",
    status: "active",
    enabled: true,
    displayOrder: 7,
    order: 7,
  },
  {
    id: "youtube-channels",
    name: "YouTube Channels",
    slug: "youtube-channels",
    icon: "youtube",
    themeColor: "#FF0000",
    color: "#FF0000",
    badgeColor: "bg-[#FF0000]/10 text-[#FF0000] border-[#FF0000]/20",
    invitePattern: "^https?:\\/\\/(youtube\\.com|youtu\\.be)\\/.+",
    helpText: "Enter YouTube Channel link",
    errorText: "Invalid YouTube URL",
    status: "active",
    enabled: true,
    displayOrder: 8,
    order: 8,
  },
  {
    id: "reddit",
    name: "Reddit",
    slug: "reddit",
    icon: "reddit",
    themeColor: "#FF4500",
    color: "#FF4500",
    badgeColor: "bg-[#FF4500]/10 text-[#FF4500] border-[#FF4500]/20",
    invitePattern: "^https?:\\/\\/(reddit\\.com|r\\.ddit)\\/.+",
    helpText: "Enter Subreddit link (reddit.com/r/...)",
    errorText: "Invalid Reddit URL",
    status: "active",
    enabled: true,
    displayOrder: 9,
    order: 9,
  },
  {
    id: "signal",
    name: "Signal",
    slug: "signal",
    icon: "signal",
    themeColor: "#3A76F0",
    color: "#3A76F0",
    badgeColor: "bg-[#3A76F0]/10 text-[#3A76F0] border-[#3A76F0]/20",
    invitePattern: "^https?:\\/\\/(signal\\.group|signal\\.me)\\/.+",
    helpText: "Enter Signal Group invite link (signal.group/...)",
    errorText: "Invalid Signal link",
    status: "active",
    enabled: true,
    displayOrder: 10,
    order: 10,
  },
  {
    id: "snapchat-groups",
    name: "Snapchat Groups",
    slug: "snapchat-groups",
    icon: "snapchat",
    themeColor: "#FFFC00",
    color: "#FFFC00",
    badgeColor: "bg-[#FFFC00]/10 text-[#111111] border-[#FFFC00]/30",
    invitePattern: "^https?:\\/\\/(www\\.)?(snapchat\\.com|add\\.snapchat\\.com)\\/.+",
    helpText: "Enter Snapchat Group link",
    errorText: "Invalid Snapchat link",
    status: "active",
    enabled: true,
    displayOrder: 11,
    order: 11,
  },
  {
    id: "slack",
    name: "Slack",
    slug: "slack",
    icon: "slack",
    themeColor: "#4A154B",
    color: "#4A154B",
    badgeColor: "bg-[#4A154B]/10 text-[#4A154B] border-[#4A154B]/20",
    invitePattern: "^https?:\\/\\/(join\\.slack\\.com|app\\.slack\\.com)\\/.+",
    helpText: "Enter Slack Workspace link",
    errorText: "Invalid Slack link",
    status: "active",
    enabled: true,
    displayOrder: 12,
    order: 12,
  },
];

export const DEFAULT_CONTENT_TYPES: ContentTypeItem[] = [
  { id: "general-discussion", name: "General Discussion", slug: "general-discussion", icon: "MessageCircle", themeColor: "#3b82f6", color: "#3b82f6", status: "active", enabled: true, displayOrder: 1, order: 1 },
  { id: "news-updates", name: "News & Updates", slug: "news-updates", icon: "Bell", themeColor: "#ef4444", color: "#ef4444", status: "active", enabled: true, displayOrder: 2, order: 2 },
  { id: "help-support", name: "Help & Support", slug: "help-support", icon: "HelpCircle", themeColor: "#10b981", color: "#10b981", status: "active", enabled: true, displayOrder: 3, order: 3 },
  { id: "learning", name: "Learning", slug: "learning", icon: "BookOpen", themeColor: "#8b5cf6", color: "#8b5cf6", status: "active", enabled: true, displayOrder: 4, order: 4 },
  { id: "jobs", name: "Jobs", slug: "jobs", icon: "Briefcase", themeColor: "#f59e0b", color: "#f59e0b", status: "active", enabled: true, displayOrder: 5, order: 5 },
  { id: "business", name: "Business", slug: "business", icon: "Building", themeColor: "#059669", color: "#059669", status: "active", enabled: true, displayOrder: 6, order: 6 },
  { id: "buy-sell", name: "Buy & Sell", slug: "buy-sell", icon: "Tag", themeColor: "#d97706", color: "#d97706", status: "active", enabled: true, displayOrder: 7, order: 7 },
  { id: "room-rent", name: "Room Rent", slug: "room-rent", icon: "Home", themeColor: "#7c3aed", color: "#7c3aed", status: "active", enabled: true, displayOrder: 8, order: 8 },
  { id: "events", name: "Events", slug: "events", icon: "Calendar", themeColor: "#ea580c", color: "#ea580c", status: "active", enabled: true, displayOrder: 9, order: 9 },
  { id: "announcements", name: "Announcements", slug: "announcements", icon: "Megaphone", themeColor: "#ec4899", color: "#ec4899", status: "active", enabled: true, displayOrder: 10, order: 10 },
  { id: "qa", name: "Q&A", slug: "qa", icon: "MessageSquareCode", themeColor: "#0284c7", color: "#0284c7", status: "active", enabled: true, displayOrder: 11, order: 11 },
  { id: "community-chat", name: "Community Chat", slug: "community-chat", icon: "Users", themeColor: "#06b6d4", color: "#06b6d4", status: "active", enabled: true, displayOrder: 12, order: 12 },
];

export const DEFAULT_LANGUAGES: LanguageItem[] = [
  { id: "hindi", name: "Hindi", code: "hi", slug: "hindi", icon: "Languages", themeColor: "#f97316", color: "#f97316", status: "active", enabled: true, displayOrder: 1, order: 1 },
  { id: "english", name: "English", code: "en", slug: "english", icon: "Languages", themeColor: "#3b82f6", color: "#3b82f6", status: "active", enabled: true, displayOrder: 2, order: 2 },
  { id: "bengali", name: "Bengali", code: "bn", slug: "bengali", icon: "Languages", themeColor: "#10b981", color: "#10b981", status: "active", enabled: true, displayOrder: 3, order: 3 },
  { id: "telugu", name: "Telugu", code: "te", slug: "telugu", icon: "Languages", themeColor: "#8b5cf6", color: "#8b5cf6", status: "active", enabled: true, displayOrder: 4, order: 4 },
  { id: "marathi", name: "Marathi", code: "mr", slug: "marathi", icon: "Languages", themeColor: "#ec4899", color: "#ec4899", status: "active", enabled: true, displayOrder: 5, order: 5 },
  { id: "tamil", name: "Tamil", code: "ta", slug: "tamil", icon: "Languages", themeColor: "#f59e0b", color: "#f59e0b", status: "active", enabled: true, displayOrder: 6, order: 6 },
  { id: "gujarati", name: "Gujarati", code: "gu", slug: "gujarati", icon: "Languages", themeColor: "#06b6d4", color: "#06b6d4", status: "active", enabled: true, displayOrder: 7, order: 7 },
  { id: "kannada", name: "Kannada", code: "kn", slug: "kannada", icon: "Languages", themeColor: "#6366f1", color: "#6366f1", status: "active", enabled: true, displayOrder: 8, order: 8 },
  { id: "malayalam", name: "Malayalam", code: "ml", slug: "malayalam", icon: "Languages", themeColor: "#14b8a6", color: "#14b8a6", status: "active", enabled: true, displayOrder: 9, order: 9 },
  { id: "punjabi", name: "Punjabi", code: "pa", slug: "punjabi", icon: "Languages", themeColor: "#ef4444", color: "#ef4444", status: "active", enabled: true, displayOrder: 10, order: 10 },
  { id: "odia", name: "Odia", code: "or", slug: "odia", icon: "Languages", themeColor: "#84cc16", color: "#84cc16", status: "active", enabled: true, displayOrder: 11, order: 11 },
  { id: "assamese", name: "Assamese", code: "as", slug: "assamese", icon: "Languages", themeColor: "#a855f7", color: "#a855f7", status: "active", enabled: true, displayOrder: 12, order: 12 },
  { id: "urdu", name: "Urdu", code: "ur", slug: "urdu", icon: "Languages", themeColor: "#059669", color: "#059669", status: "active", enabled: true, displayOrder: 13, order: 13 },
  { id: "sanskrit", name: "Sanskrit", code: "sa", slug: "sanskrit", icon: "Languages", themeColor: "#d97706", color: "#d97706", status: "active", enabled: true, displayOrder: 14, order: 14 },
  { id: "other", name: "Other", code: "other", slug: "other", icon: "Languages", themeColor: "#64748b", color: "#64748b", status: "active", enabled: true, displayOrder: 15, order: 15 },
];

export const DEFAULT_LOCATION_STATES: LocationState[] = INDIA_STATES.map((st, idx) => ({
  id: st.name.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-"),
  name: st.name.trim(),
  slug: st.name.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-"),
  country: "India",
  enabled: true,
  status: "active",
  displayOrder: idx + 1,
}));

export const DEFAULT_LOCATION_DISTRICTS: LocationDistrict[] = INDIA_STATES.flatMap((st) =>
  st.districts.map((distName, dIdx) => ({
    id: `${st.name}-${distName}`.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-"),
    stateId: st.name.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-"),
    stateName: st.name.trim(),
    name: distName.trim(),
    slug: distName.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-"),
    country: "India",
    enabled: true,
    status: "active",
    displayOrder: dIdx + 1,
  }))
);
